### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by theaspect** [Stig4all/Engin#11]
1. В приложении не должно быть бинарных артефактов
2. Папки в которые компилируются артефакты должны быть в `.gitignore`
3. Компилируйте руками, мавен только в третьем наборе требований
4. Продублированы классы
5. Вместо HashMap создайте класс в 8 полями и возвращайте его
6. В коде не должно быть deprecated классов
7. Зачем инициализируется поле cmd Input.java:29
8. Строки Main.java:25 и Main.java:26 можно объединить в одну (используйте refactor->inline) (смотри пункт 14 ниже)
9. Соль должна быть уникальная и случайная для каждого юзера
10. При генерации хэша подавляется исключение (заверните в RuntimeException и прокиньте дальше)
11. замените for на foreach там где индексы не нужны
12. в коде не должно быть неиспользуемых и закомментированных методов
13. validtime и validvalue должны быть camelCase-ом
14. в Input option не должны быть статическим полем

**Comment by reegly** [comment]
Done 
#1
#4
#12
#13

**Comment by reegly** [comment]
#5
#7
#14
